#!/usr/bin/python
# -*- coding: utf8 -*-


import requests
import subprocess
import time
import uuid
import os

base_url = "http://alfem.pythonanywhere.com/"
sleep_time=10

hostname=os.uname()[1]

with open("/etc/pclabel") as f:
    pclabel=f.readline()


uid=uuid.uuid1()

print "HOSTNAME:", hostname
print "PC LABEL:", pclabel
print "SESSION ID:", uid

ses = requests.Session()
ses.headers = {'hostname':hostname,'pclabel':pclabel,'sessionid':uid}

last_command=""

while True:
   resp=ses.get(base_url+"client",headers=ses.headers)
   
   print resp.status_code
   print resp.text   

   command=resp.text
   if command != "" and command != last_command:
       output=open("/tmp/unamano.log","w")
       subprocess.call(command,stdout=output,stderr=subprocess.STDOUT,shell=True)
       output.close()
       files = {'output': open('/tmp/unamano.log','rb')}
       data = {"uid":uid }
       resp=ses.post(base_url+"client",data=data,files=files,headers=ses.headers)

       print resp.status_code
       last_command=command
   
   print "Sleeping for",sleep_time,"seconds"
   time.sleep(sleep_time)
   
   
